### ISSUE TITLE
create better pattern for capturing shapefile files as dependencies

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#182]
right now we have the creation (or modification) of a shapefile return a vector of file paths from the function that creates it or modifies it. I thought this was ok, but ran into an issue where `remake` wasn't updating targets that should change when the shapefile changes. This is because remake is looking at the vector of file names and seeing no changes to that vector, as opposed to seeing the return as a set of file paths and looking to detect changes there instead. 

This seems relevant mostly for shapefiles, because other file types (like `tsv`) return a single file path and we use that as the target. 

in the remake file, this looks like this:
```yaml
catchment_metadata:
    command: extract_feature(site_catchment_shapefile) # is vector of file names
```

Possible solutions: 

- return a slightly more complex object in R that may be a list (e.g., `list(files = c(...), hash = 'asdfwef#')` that would have a checksum or something (dateTime modified even) of when the file changed)
- Keep the shapefile as an sp object, and only write to file just before posting the files to SB
- ask other users of remake what they do
- list all files in the dependencies of these targets (seems like too much effort)

@aappling-usgs thoughts? This seems worth thinking about since it will come up w/ other projects (maybe vizlab if we aren't careful) and it would be nice to converge on a single pattern.

**Comment by aappling-usgs** [comment]
I like the timestamp option best - it's memory efficient, gives us another way to manually inspect the status of the analysis, and is fairly similar to the status file approach we're using elsewhere in the repo.

One modification of your option 2 would be to write to file within the function but return the R object rather than (or in addition to) the file names.

A third option would be to only return one of the shapefile filenames, if that file can be relied on to change when the contents of the shapefile change. This would require some insider spatial data storage knowledge - do you know if there is one such file? The generic version of this approach is to let remake commands write to multiple files but only use one as a sentinel to indicate whether the command has been run. I've used that general approach before, usually without mishap, but it's the least comprehensive of the options we've listed.

**Comment by jread-usgs** [comment]
Yeah, I was thinking of your third option two, but I think there are at least two files that could have independent changes that wouldn't alter the other- geometry changes that don't alter the number of features would change the .shp but not the .dbf, and changes to the values of the attributes or the number of attributes would change the .dbf but not the .shp. Both of those don't even seem that far out to be considered edge-cases, so I don't think it would work that way.

For the second option I had above - I think it should either be an sp object or written to file. Doing both could result in unchecked deviations to one (probably the file) that don't trigger a downstream target rebuild if it gets messed w/ manually. I think I prefer the option of keeping `sp` and posting an `sp` writes to a temp set of files and posts them to SB. 

Sound good?

**Comment by aappling-usgs** [comment]
Yep, sounds good.

**Comment by jread-usgs** [comment]
there is discussion of this here: https://github.com/richfitz/remake/issues/10
