### ISSUE TITLE
Respond to metadata and data reviews

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#253]
- [x] AA Complete fits from metabolism estimation models
- [x] AA Daily metabolism estimates and predictors
- [x] ~~JR~~ AA Input data used for estimating metabolism
- [x] AA Key diagnostics and overall assessments of metabolism model performance
- [x] ~~JR~~ AA Model configurations for estimating metabolism
- [x] JR+AA Site identifiers and details
- [x] JR Spatial catchments
- [x] JR Spatial site locations
- [x] AA Timeseries data collected or computed from outside sources, for estimating or interpreting metabolism

Add comments at https://drive.google.com/drive/folders/164krY1egxtichgnPohq0dv3I5Y8wdi0X

**Comment by jread-usgs** [comment]
#### general
Noted the bounding box north south is flipped...what is the deal w/ that? `meddle`?

#### for JR Spatial catchments,

AK, WA, and CA seem to be missing. I want to get into the guts of the overlap GIS code that is used to extract those names, but ran into an error. This will likely be a `meddle` bug fix
Also parent SB ID in the code is [57adfa86e4b0fc09faad6d87](https://github.com/USGS-CIDA/stream_metab_usa/blob/master/remake/4_release_parent.yml#L58), but the release seems to live here: [5a5e37bbe4b06e28e9be48c6](https://www.sciencebase.gov/catalog/item/59bff507e4b091459a5e0982)


#### for JR Spatial points,

PR is missing, likely because meddle doesn't include the territory in the overlap lookup. 

#### for JR Input data used for estimating metabolism:

Mike found negative discharge sites, which is expected. The negative DO is something I am looking into, but I think it is better to lean on releasing "approved" USGS records regardless of what the value is. 
Note the Placenames will need to be updated (this is likely captured by the remake dependencies) when the Spatial points metadata file is updated if it should also include PR. 
add text to explain -999999 is an error code for water temperature data.

#### JR Site identifiers and details
Look into the repeated sets of coefficients and nhd reach codes. Hopefully this is the case of multiple sites being on the same reach. 
Plot all 13 sites that have a 0 altitude value to spot check they are all in locations where this would make sense. If not, cross-check NWIS site file info. 
For NID dataset, mike notes the online linkage we provide doesn't help users of the dataset. Use http://nid.usace.army.mil/ instead?
for NPDES seems we should replace w/ https://www.epa.gov/npdes and keep fighting the good fight with the shifting sands of URLs....
add site_type to process description
Change altitude datum to "vertical datum" (attr def)

#### JR Model configurations for estimating metabolism
"Model configurations for estimating metabolism. Configuration parameters can be" is incomplete text



I will be chipping away at the above ☝️

**Comment by jread-usgs** [comment]
Spatial points and catchments reconciliation is done. PR coming later (for this and `meddle`)

**Comment by jread-usgs** [comment]
Spot checked these and, as expected, the "Altitude of Gage/land surface" is 0. E.g., https://waterservices.usgs.gov/nwis/site/?site=0209303205

**Comment by aappling-usgs** [comment]
Need to get # of points correct for model metadata files. https://github.com/USGS-CIDA/stream_metab_usa/pull/275#issuecomment-392272385

**Comment by aappling-usgs** [comment]
@jread-usgs - `Site identifiers and details` is nearly complete - I think the only two issues that could still be responded to in https://docs.google.com/document/d/1ZTgcEQ7MQppbvxqI_zbFMgpAyv8ch5sKAqVaZ8pCbqk/edit?usp=sharing are 
* the "lack of formal reports of data accuracy, consistency or completeness" (optional response) and
* the status of the altitude=0 data.
And if you had responses prepared that differ substantially from mine for any other issues, feel free to override my responses.

**Comment by jread-usgs** [comment]
These should be done now. PR coming w/ small edits
