### ISSUE TITLE
track down sites w/o lon/lat data

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#8]
e.g., `09327000` and `411959088280101`

These are NA on `readNWISsite(site = '09327000')`

**Comment by aappling-usgs** [comment]
interesting - site 411959088280101 is no longer in SB.
```
which(list_sites()=="nwis_411959088280101")
```
there's a similarly numbered site, nwis_411955088280601, for which data _are_ available. and 09327000 still needs help. 
```
sites <- list_sites(); coords <- find_site_coords(sites)
coords[coords$site_name %in% c("nwis_09327000", "nwis_411959088280101","nwis_411955088280601"), ]
               site_name      lat       lon
U                            degN      degE
481        nwis_09327000      NaN       NaN
604 nwis_411955088280601 41.33306 -88.46694
```
https://github.com/USGS-R/mda.streams/issues/117 will address this one. closing this issue because we now know which sites need help.
